### PR TITLE
Jongsy/fix multiple experiment event params

### PR DESCRIPTION
**Pull request by jongsy**

### CODE REVIEW

**Comment by aliabbasrizvi** [comment]
@jongsy thank you for submitting this fix. Taking a look at this. Can you please sign our CLA here: https://docs.google.com/a/optimizely.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform

**Comment by jongsy** [comment]
@aliabbasrizvi No problem. I've signed the CLA

**Comment by aliabbasrizvi** [comment]
Thanks @jongsy . I pulled your changes and merged them as part of #136 .

We will be publishing a new version of the SDK. I will respond here as soon as that happens.
Thank you again for flagging this issue and submitting a fix as well. Really appreciate it.

**Comment by aliabbasrizvi** [comment]
@jongsy patched the issue and fix is available in SDK 2.1.1: https://pypi.org/project/optimizely-sdk/2.1.1

Thank you again for sending the fix over.

**Pull request closed without merging**
