### PR TITLE
fix(exception-handling): Fix handling of network and other non-status-code errors when polling for datafile

### PR DESCRIPTION
**Pull request by benweissmann**
Summary
-------

- https://github.com/optimizely/python-sdk/pull/285 was an incomplete fix; as per [the docs](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts), timeouts and other network errors throw on the call to `.get()`, not on the call to `.raise_for_status()` (`raise_for_status` just checks for a non-2xx HTTP return code; it doesn't handle other kinds of errors)

- This adds additional error handling around calls to `requests.get`.

- Also made a small tweak to the README; `zsh` requires quoting around `.[test]`.

Test plan
---------

- Added unit tests for both the polling config manager and the static config manager

### CODE REVIEW

**Comment by benweissmann** [comment]
It looks like CI is failing because of a missing credential -- maybe because I'm an outside contributor? The tests do pass on my machine.

**Comment by aliabbasrizvi** [comment]
@benweissmann thank you for submitting this change and signing our CLA. I will review this as soon as possible and get a release out.

**Comment by aliabbasrizvi** [comment]
Tests succeeded here: https://travis-ci.org/github/optimizely/python-sdk/builds/708071108

Merging change.

**Comment by aliabbasrizvi** [comment]
@benweissmann just released updated SDK 3.5.2 with your change.

**Pull request merged**
