### PR TITLE
feat: BatchEventProcessor as Default Event Processor

### PR DESCRIPTION
**Pull request by ozayr-zaviar**
Summary
-------
- ForwardingEventProcessor sends calls in a synchronous manner so to reduce the time it is replaced with BatchEventProcessor which sends calls in an asynchronous manner.

Test plan
---------
- All unit tests and FSC tests should pass.

### CODE REVIEW

**Review by msohailhussain — APPROVED** [review]
lgtm

**Comment by andrewleap-optimizely** [comment]
@msohailhussain made some small changes to fix the broken tests and make the api more intuitive.

**Review by andrewleap-optimizely — APPROVED** [review]
lgtm

**Review by msohailhussain — APPROVED** [review]
lgtm

**Pull request merged**
