### PR TITLE
[FSSDK-8954] docs: change full stack to feature experimentation

### PR DESCRIPTION
**Pull request by andrewleap-optimizely**
Summary
-------

-  Updates readme and setup.py replacing Full Stack with Feature Experimentation

Test plan
---------
All tests should pass.

Ticket
------

[FSSDK-8954](https://jira.sso.episerver.net/browse/FSSDK-8954)

### CODE REVIEW

**Comment by griffincox-optimizely** [comment]
Reviewed the code changes and eye-ball checked the rendered MD. LGTM, no comments. Wow.

**Review by russell-loube-optimizely — COMMENTED** [review]
lgtm - please get fellow developer to approve.

**Review by griffincox-optimizely — COMMENTED** [review]
LGTM with link fix

**Review by Mat001 — APPROVED** [review]
Looks good. No sdk breaking changes.

**Pull request merged**
